# -*- coding: utf-8 -*-
"""model.pkl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPFEIUUr3VONBUxsdurqFcPxtU1UC-h6
"""

from sklearn.linear_model import LinearRegression
import numpy as np
import joblib

# dummy training data
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

# save with protocol 4 (Render ki perfect)
joblib.dump(model, "model.pkl", protocol=4)

print("New model.pkl saved successfully!")

